#!/bin/bash
tr -d '\n' | tr [:upper:] [:lower:] | sed "s/\`/\'/g" | \
sed -e "s/<\/*u>//g" | grep -o "<tr> \+<td>[^<]*</td> \+<td>[^<]*</td>" | \
awk -F '    ' '{print $3}' | sed "s/<\/*td>//g" | sed "s/,* /\n/g" | \
sed '/^$/d' | sort -u | comm -23 - words

